import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-pink-500 text-white p-4">
         <Navigation /> 
          {/* <p>Welcome to Next.js Demo</p> */}
        </header>
        {children}
        <footer className="bg-gray-200 text-center p-4 mt-8">
          <p>&copy; 2024 Next.js Demo  </p>
          </footer>
      </body>
    </html>
  );
}
